### ISSUE TITLE
Update README with these build instructions

### ISSUE THREAD

**Issue by grigorescu** [robertdavidgraham/rdpscan#1]
This invocation worked for me with Homebrew OpenSSL:

`gcc $(brew --prefix)/opt/openssl/lib/libssl.a $(brew --prefix)/opt/openssl/lib/libcrypto.a -o rdpscan *.c`

**Comment by robertdavidgraham** [comment]
I still get those linkking errors, because my machine is messed up. However, I did add your comment to the README.md.
