### ISSUE TITLE
Timestamp in addition to scan result

### ISSUE THREAD

**Issue by acbekoac** [robertdavidgraham/rdpscan#10]
As IP's are randomized, it would be nice/handy to put a  timestamp (like "date -R") in front of each line to get something like

Wed, 29 May 2019 13:51:27 +0200 - 211.101.37.250 - SAFE - CredSSP/NLA required
Wed, 29 May 2019 13:52:21 +0200 - 106.12.74.155 - VULNERABLE - got appid

**Comment by robertdavidgraham** [comment]
You can now use either the --gmtime or --localtime parameter to get timestamps in either GMT or your local timezone. They are of the form:

2019-05-29 13:52:27 - SAFE - CredSSP/NLA Required
