### ISSUE TITLE
Unencrypted connections, CentOS, timestamps

### ISSUE THREAD

**Issue by jenhek** [robertdavidgraham/rdpscan#13]
It would be nice to see in the non-debug (aka regular) log,
whether a connection was done without SSL as this opens up
the vulnerabilty of being sniffed.

Furthermore it would be nice to enforce an unencrypted connection
to see, what systems still support that.

And 2¢ for CentOS: I had to add "-lrt" on that platform for linking.
(maybe one for the doc).

And, as my colleague already stated: timestamps in the logs are recommended.

**Comment by robertdavidgraham** [comment]
1. use --gmttime (or --localtime) for timestamps.
2. I've changed clock_gettime() to gettimeofday(), so -lrt on CentOS 6.10 is no longer necessary.
3. I added the --noencrypt and --nossl options to try and force no encryption, but then targets drop the connection. I'm still trying to figure out how to force a non-encrypted conneciton.
