### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by patricksaladino** [robertdavidgraham/rdpscan#15]
Hello,

Could you please update the readme file to instruct people using older versions of glibc to link the real-time library ("-lrt") when compiling rdpscan ? For example, under CentOS 6.10 :

`gcc  *.c -lssl -lcrypto -o rdpscan` fails with the error message `./dev/rdpscan/src/util-time.c:28: undefined reference to 'clock_gettime'`

When using ` gcc *.c -lssl -lcrypto -lrt -o rdpscan`, it works like a charm

Best regards,
P.

**Comment by robertdavidgraham** [comment]
I fixed this by changing `clock_getttime()` to `gettimeofday()`. I tested on CentOS 6.10 and now it compiled just fine. OMG, that's back on kernel version 2.6, so old!!!

**Comment by patricksaladino** [comment]
Well, thanks for the quick fix ! I'm in the process of migrating all of my stuff to a more recent version of CentOS but it's a real pain in the ***.
