### ISSUE TITLE
2019

### ISSUE THREAD

**Issue by kouzhudong** [robertdavidgraham/rdpscan#16]
1>------ 已启动生成: 项目: rdpscan, 配置: Debug x64 ------
1>asn.c
1>c1: fatal error C1083: 无法打开源文件: “..\asn.c”: No such file or directory
1>bitmap.c
1>c1: fatal error C1083: 无法打开源文件: “..\bitmap.c”: No such file or directory
1>channels.c
1>c1: fatal error C1083: 无法打开源文件: “..\channels.c”: No such file or directory
1>iso.c
1>c1: fatal error C1083: 无法打开源文件: “..\iso.c”: No such file or directory
1>licence.c
1>c1: fatal error C1083: 无法打开源文件: “..\licence.c”: No such file or directory
1>main.c
1>c1: fatal error C1083: 无法打开源文件: “..\main.c”: No such file or directory
1>mcs.c
1>c1: fatal error C1083: 无法打开源文件: “..\mcs.c”: No such file or directory
1>mppc.c
1>c1: fatal error C1083: 无法打开源文件: “..\mppc.c”: No such file or directory
1>mst120.c
1>c1: fatal error C1083: 无法打开源文件: “..\mst120.c”: No such file or directory
1>orders.c
1>c1: fatal error C1083: 无法打开源文件: “..\orders.c”: No such file or directory
1>rand-blackrock.c
1>c1: fatal error C1083: 无法打开源文件: “..\rand-blackrock.c”: No such file or directory
1>ranges.c
1>c1: fatal error C1083: 无法打开源文件: “..\ranges.c”: No such file or directory
1>rdp.c
1>c1: fatal error C1083: 无法打开源文件: “..\rdp.c”: No such file or directory
1>rdp5.c
1>c1: fatal error C1083: 无法打开源文件: “..\rdp5.c”: No such file or directory
1>secure.c
1>c1: fatal error C1083: 无法打开源文件: “..\secure.c”: No such file or directory
1>ssl.c
1>c1: fatal error C1083: 无法打开源文件: “..\ssl.c”: No such file or directory
1>tcp.c
1>c1: fatal error C1083: 无法打开源文件: “..\tcp.c”: No such file or directory
1>util-genrand.c
1>c1: fatal error C1083: 无法打开源文件: “..\util-genrand.c”: No such file or directory
1>util-log.c
1>c1: fatal error C1083: 无法打开源文件: “..\util-log.c”: No such file or directory
1>util-sockets.c
1>c1: fatal error C1083: 无法打开源文件: “..\util-sockets.c”: No such file or directory
1>正在生成代码...
1>正在编译...
1>util-time.c
1>c1: fatal error C1083: 无法打开源文件: “..\util-time.c”: No such file or directory
1>util-xmalloc.c
1>c1: fatal error C1083: 无法打开源文件: “..\util-xmalloc.c”: No such file or directory
1>workers.c
1>c1: fatal error C1083: 无法打开源文件: “..\workers.c”: No such file or directory
1>正在生成代码...
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(429,5): error MSB6006: “CL.exe”已退出，代码为 2。
1>已完成生成项目“rdpscan.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by BrendanGrant** [comment]
I encountered that same problem yesterday and made a PR for it today, want to give it a try? https://github.com/robertdavidgraham/rdpscan/pull/17

**Comment by robertdavidgraham** [comment]
Should be fixed now.

**Comment by robertdavidgraham** [comment]
Also, thanks for the pull request so i didnt' have to go do it :-)
