### ISSUE TITLE
Scan non default port

### ISSUE THREAD

**Issue by iummit** [robertdavidgraham/rdpscan#23]
Please add functionality to test alternate ports for testing non-default RDP assignment

**Comment by TheGn0m3** [comment]
Yes this would be very helpful since I use non standard ports for RDP.

Thanks In advanced.

**Comment by robertdavidgraham** [comment]
This is already supported. If scanning for port 3333, then add the option "--port 3333"

**Comment by wrolisonaflac** [comment]
> This is already supported. If scanning for port 3333, then add the option "--port 3333"

Perhaps mention in ReadMe ?

**Comment by TheGn0m3** [comment]
@robertdavidgraham  can we use 2 ports at once?

Regards.

**Comment by iummit** [comment]
> @robertdavidgraham can we use 2 ports at once?
> 
> Regards.

No.  I tried the following and it did not work as expected:
-p 3390,3389 <--- scanned port 3390 only
-p 3389 -p 3390  <--- scanned port 3390 only

I guess I need to fork it and start reading source.
