### ISSUE TITLE
Win2003 dies with procedure entry point inet_ntop could not be located in ws2_32.dll

### ISSUE THREAD

**Issue by AlexHeylin** [robertdavidgraham/rdpscan#4]
Thanks very much for this code! 

Minor, but for completeness, if trying to run on Win2003 it dies with:
The procedure entry point inet_ntop could not be located in the dynamic link library ws2_32.dll

![image](https://user-images.githubusercontent.com/270973/58484175-79f9d780-8159-11e9-9bdc-4f5ab14ab319.png)

**Comment by robertdavidgraham** [comment]
Yea, it works only on Windows Vista and above, not WinXP era machines. It's because it supports IPv6 while WinXP doesn't.

**Comment by ignis-sec** [comment]
I have so many questions about how and why you are still using windows 2003

**Comment by robertdavidgraham** [comment]
As they said, "for completeness". I already tried this on WinXP myself :-).

**Comment by ignis-sec** [comment]
Oh, missed the completeness part. I was really baffled for a second with the thought that someone was trying to do vulnerability scanning with a windows 2003 machine.

**Comment by AlexHeylin** [comment]
Actually I was trying to scan from Win2003 machine. My ideal use case would be to scan 127.0.0.1 from each machine in question, which includes machines running 2003 / XP - because of reasons. 

Thanks for clarify cause. I'd have a go at modifying to check for this before trying to load but I can barely read C++ let alone write it.

**Comment by robertdavidgraham** [comment]
I have fixed it. The latest binary should probably now work. It seems to have issues with large network ranges when run from WinXP, but scanning 127.0.0.1 now appears to work at least.

**Comment by AlexHeylin** [comment]
Thanks so much Robert! :-D
