### ISSUE TITLE
ubuntu: [-] fork() hit process limit - when run via system search path

### ISSUE THREAD

**Issue by meagercreek** [robertdavidgraham/rdpscan#8]
Under "Ubuntu 18.04.2 LTS" the tool behaves normal when called with path prefix like "./rdpscan 10.1.2.0/24" or "/usr/local/bin/rdpscan 10.1.2.0/24".

When called without path prefix ("rdpscan 10.1.2.0/24") so that the binary is found via system search path then it endlessly forks child processes until the message "[-] fork() hit process limit" shows up and no new processes can be forked under any user anymore.
Running as root or giving the "--workers" parameter does not change this behaviour. It can be stopped with CTRL+C and all spawned processes cleanly disappear. Tcpdump shows that none of these processes actually starts sending out packets.

**Comment by robertdavidgraham** [comment]
What does ps -ax | grep rdpscan say?

**Comment by meagercreek** [comment]
When I run "rdpscan 10.1.2.0/24" and the ps command is issued fast enough it lists thousands of entries like this:
[...]
1033110 pts/2    S+     0:00 rdpscan 10.1.2.0/24
1033111 pts/2    S+     0:00 rdpscan 10.1.2.0/24
1033112 pts/2    S+     0:00 rdpscan 10.1.2.0/24
1033113 pts/2    S+     0:00 rdpscan 10.1.2.0/24
1033114 pts/2    S+     0:00 rdpscan 10.1.2.0/24
[...]

When started too late the answer is "-bash: fork: retry: Resource temporarily unavailable".

**Comment by ralphyz** [comment]
I have the same issue on Kali (Debian).  If I run with the full path, I get results.

root@hostname#uname -a
Linux hostname 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

root@hostname# cat /etc/issue
Kali GNU/Linux Rolling \n \l

root@hostname# cat /etc/*-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.1"
VERSION_ID="2019.1"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Comment by robertdavidgraham** [comment]
I'm still working on this with my copy of Kali. So far I can't reproduce. So far I've tried on:
Linux kali 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux

**Comment by robertdavidgraham** [comment]
I fixed this. The problem was that I wasn't checking the return code of exec(), assuming it alway succeeded. If it failed, then I kept on forking more processes. This is very bad coding :-).
